public class ProfileCard {
    
    public static void main(String[] args) {
        System.out.println("CS 234-JAVA PROFILE CARD");
        for(int i=0;i<=32;i++){
            System.out.print("=");
        }
        System.out.println("");
        System.out.println("Name        :"+"Juhudi");
        System.out.println("Student ID  :"+"2024-04-03712");
        System.out.println("Year        :"+"2nd year");
        for(int i=0;i<=32;i++){
            System.out.print("-");
        }
        System.out.println("");
        System.out.println("Background     :"+"I know Java and C from CS175 and I built simple projects");
        for(int i=0;i<=32;i++){
            System.out.print("-");
        }
        System.out.println("");
        System.out.println("Goal           :"+"I want to become a backend developer with java concepts");
        for(int i=0;i<=32;i++){
            System.out.print("-");
        }
        System.out.println("");
        System.out.println("Fan Fact       :"  + "I can generate code of a crtain project under the absence of AI");
        for(int i=0;i<=32;i++){
            System.out.print("=");
        }
        System.out.println("");
    }
    
}
